---
abstract: 'Simple DBI wrapper'
author:
  - 'Masahiro Nagano <kazeburo {at} gmail.com>'
build_requires:
  Capture::Tiny: 0
  DBD::SQLite: 1.31
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.96
  Test::Requires: 0
  Test::TCP: 0
  Test::mysqld: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Sunny
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Lite: 0.05
  Class::Data::Inheritable: 0
  DBI: 1.615
  DBIx::TransactionManager: 0
  Data::Validator: 0
  parent: 0
  perl: 5.8.5
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kazeburo/DBIx-Sunny.git
version: 0.18
